#!/bin/bash

DEST=schema.prisma

# Ensure we are in this files directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd "$DIR"

echo "// This file generated by schemaGen.sh" > $DEST
cat datasource.prisma >> $DEST
find ../src -type f -name "*.prisma" -exec cat {} >> $DEST \;

echo "SUCCESS: Prisma Schema Generated"